FirstWebPage/Controllers/ArticleController.cs
using FirstWebPage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstWebPage.Controllers
{
    public class ArticleController : Controller
    {
        public ContentResult Index()
        {
            return new ContentResult() { Content = "Привет" };
        }
        public ContentResult GetByUrl(string seoUrl) 
        {
            return new ContentResult() { Content = "#" + seoUrl + "#"};
        }

        public ActionResult Recent()
        {
            var model = new RecentDataModel();
            return View(model);
        }

    }
}

FirstWebPage/Controllers/CommentController.cs
using FirstWebPage.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstWebPage.Controllers
{
    public class CommentController : Controller
    {
        
        public ActionResult Recent()
        {
            var model = new RecentDataModel();
            return View(model);
        }
       public ContentResult Index()
        {
            return new ContentResult() { Content = "Привет" };
        }
        public ContentResult ById(int id)
        {
            return new ContentResult() { Content = "Это коментарий #" + id };
        }
        

    }
}

FirstWebPage/Views/Shared/RecentComments.cshtml
@{
    Layout = null;
}
@model FirstWebPage.Models.RecentDataModel

<div id="comments">
    <div class="lthead" align="center"><span class="tphead">Последние комментарии</span></div>
    <ul>
        @foreach (var item in Model.Items)
        {
            <li>
                <p class="date"><span>@item.Date.ToString("D")</span> <span>@item.Date.ToString("hh:mm")</span></p>
                <p class="post"><a href="@item.URL">@item.Text</a></p>
            </li>
        }
    </ul>
</div>

FirstWebPage/Views/Shared/RecentPosts.cshtml
@{
    Layout = null;
}

<!--Собственная часть предсталения с другим типом модели RecentDataModel являющ.свойством модели Layout-->
@model FirstWebPage.Models.RecentDataModel

<div id="mostpop">
    <div class="lthead"><span>Последние посты</span></div>
    <ul>
        @foreach (var item in Model.Items)
        {
            <li>
                <p class="date">@item.Date.ToString("D")</p>
                <p class="post"><a href="@item.URL">@item.Text</a></p>
            </li>
        }
    </ul>
    <div class="clear"></div>
</div>

FirstWebPage/Views/Shared/_Layout.cshtml
 <!--Мастер страница(контейнер,в который вставляется наша страница)-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Блог</title>
    <link rel="stylesheet" type="text/css" href="~/Content/css/style.css" />

</head>
<body>
    
    <div id="wrapper">
       
        <div id="container">
            <!--Левая колонка-->
            <div id="left">
                <!--hdlogo starts-->
                <div id="hdlogo" align="center">
                    <img src="~/Content/images/topbanner.jpg" alt="" />
                </div>
                <!--hdlogo ends-->

                <div class="ltgap"></div>
                <!-- search starts-->
                <div id="search">
                    <div class="input">
                        <input type="text" name="search" class="textbox" /> <input type="submit" value="ПОИСК" class="searchBut" />
                    </div>
                </div>
                <!--search ends-->

                <div class="ltgap"></div>
                    @Html.Action("Recent", "Article")
                <div class="ltgap"></div>
                    @Html.Action("Recent", "Comment")
                <div class="ltgap"></div>

            </div>
            <!--Правая колонка-->
            <div id="right">
                
                <div class="publish">Капля никотина убивает лошадь. А чашка кофе - клавиатуру</div>
                
                <div class="head">Блог сис админа</div>
                
                <div id="menulinks">
                    <ul>
                        <li>@Html.ActionLink("Последний", "Index", "Home", null, null)</li>
                        <li>@Html.ActionLink("Архив", "History", "Home", null, null)</li>
                        <li>@Html.ActionLink("О блоге", "About", "Home", null, null)</li>
                        @*<a href="@Url.Action("ById", "Comment", new {id = item.ID})">Hello!!!!</a>*@
                        @*Html.ActionLink("World!!!!!", "ById", "Comment", new { id = item.ID }, null)  null-атрибуты для ссылки например класс *@ 
                        @*<a href="@Url.RouteUrl("default1", new { controller = "Comment", action = "ById", id = item.ID })">@item.Text</a>*@
                        @*@Html.RouteLink("Hello from Mars", "article", new { seoUrl = item.Text })*@
                        
                    </ul>
                </div>
                <div class="clear"></div>
                @RenderBody() <!--директива, которая “рисует”, собственно, тот View, для которого работает данный Layout.-->
                <br />

            </div>
            <div id="footer"></div>
        </div>
        
    </div>
</body>
</html>